"use client";

import "./globals.css";
import Link from "next/link";
import { useEffect, useState } from "react";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isScrolled, setIsScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 100) {
        setIsScrolled(true);
      } else {
        setIsScrolled(false);
      }
    };

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  return (
    <html lang="en">
      <body className="antialiased">
        <nav
          className={`px-20 flex items-center justify-between bg-white ${
            isScrolled ? "fixed top-0 w-full shadow-lg py-4" : "py-8"
          } z-50`}
        >
          <div className="flex items-start gap-4">
            <h1 className="font-extrabold text-3xl uppercase text-blue-600">
              Ahmad
            </h1>
            <div className="w-2 h-2 rounded-full bg-blue-500"></div>
          </div>
          <div className="space-x-10 font-bold text-sm uppercase">
            <a href="#" className="hover:text-blue-600">
              Home
            </a>
            <a href="#about" className="hover:text-blue-600">
              About
            </a>
            <a href="#skills" className="hover:text-blue-600">
              Skills
            </a>
            <a href="#services" className="hover:text-blue-600">
              Services
            </a>
            <a href="#portofolio" className="hover:text-blue-600">
              Portofolio
            </a>
            <a href="#contact" className="hover:text-blue-600">
              Contact
            </a>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
