"use client";

import "./globals.css";
import Link from "next/link";
import { useEffect, useState } from "react";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isScrolled, setIsScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 100) {
        setIsScrolled(true);
      } else {
        setIsScrolled(false);
      }
    };

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  return (
    <html lang="en">
      <body className="antialiased">
        <nav
          className={`py-8 px-20 flex items-center justify-between bg-white ${
            isScrolled ? "fixed top-0 w-full shadow-lg" : ""
          }`}
        >
          <h1 className="font-extrabold text-3xl uppercase text-blue-600">
            Ahmad
          </h1>
          <div className="space-x-10 font-bold text-sm uppercase">
            <Link href="/" className="hover:text-blue-600">
              Home
            </Link>
            <Link href="/about" className="hover:text-blue-600">
              About
            </Link>
            <Link href="/services" className="hover:text-blue-600">
              Services
            </Link>
            <Link href="/portofolio" className="hover:text-blue-600">
              Portofolio
            </Link>
            <Link href="/pages" className="hover:text-blue-600">
              Pages
            </Link>
            <Link href="/blog" className="hover:text-blue-600">
              Blog
            </Link>
            <Link href="/contact" className="hover:text-blue-600">
              Contact
            </Link>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
